### PR TITLE
Tooltip content change observer added

### PR DESCRIPTION
**Pull request by csprocket777**

### CODE REVIEW

**Comment by yankeeinlondon** [comment]
Hi @csprocket777 was away for a long weekend but taking a look at your PR now. Can you give me a quick one-liner explanation for what this is providing?

**Comment by csprocket777** [comment]
I have since made more modifications to this but am terrible at PRs and squashing commits. The intent was to get the tooltip to update when the content changes, which it didn’t seem to do automatically for me.

**Comment by yankeeinlondon** [comment]
Yeah I guess I probably didn't test that use case. The problem I see with your code right now is that while you are destroying the observer when the component exits, we're not destroying the old Bootstrap tooltip when an update to the `tooltip` property comes along.

**Comment by csprocket777** [comment]
That was something I added to my own fork but didn't submit subsequent pull requests until I had it all settled.

Chuck

**Comment by yankeeinlondon** [comment]
Hey apologies that I let this slip ... I'm accepting now. Will make a quick npm push and then upgrade to Ember 1.13 and CLI 1.13.7

**Comment by yankeeinlondon** [comment]
use version 0.0.18 on master for this ... now upgrading to Glimmer

**Pull request closed without merging**
